= The Tyto Project

The Tyto Project is a collection of open source FPGA designs and IP for retro computing and embedded systems.

At present, the designs target *Xilinx 7-Series* FPGAs, and the *Digilent Nexys Video* board, with some support for the *QMTECH Wukong* board. Development is done with the free editions of Xilinx Vitis and Vivado (version *2020.x*) on Windows 10. Note that Vitis is only required for designs that include a MicroBlaze CPU.

== Designs

=== mb_audio_io

A MicroBlaze CPU interfaced to an I^2^S audio codec. <<./doc/mb_audio_io/mb_audio_io.adoc#,More...>>

Supports: Digilent Nexys Video

=== mb_display_sd

A MicroBlaze CPU with a standard definition character display, similar to the text modes of a PC VGA adapter. <<./doc/mb_display_sd/mb_display_sd.adoc#,More...>>

Supports: Digilent Nexys Video, QMTECH Wukong

=== hdmi_tpg

An HDMI video test pattern generator, supporting resolutions from SD to full HD. Also generates an audio test tone. <<./doc/hdmi_tpg/hdmi_tpg.adoc#,More...>>

Supports: Digilent Nexys Video, QMTECH Wukong

=== np65_poc

A proof-of-concept demonstration of the <<./doc/np65/np65.adoc#,np65>> 6502 compatible CPU core. Runs Klaus Dormann's 6502 functional test code in a loop, incrementing an 8 bit LED pattern each time round. Shows a 150x speedup compared with the classic 1MHz NMOS 6502. <<./doc/np65_poc/np65_poc.adoc#,More...>>

Supports: Digilent Nexys Video, QMTECH Wukong

=== ddr3_test

A simple DDR3 SDRAM tester based on https://github.com/jorisvr/vhdl_prng[Joris van Rantwijk's Pseudo Random Number Generator]. Also demonstrates the addition of user defined clocks, including the 200MHz IODELAYCTRL reference clock, to the DDR3 IP core MMCM. <<./doc/ddr3_test/ddr3_test.adoc#,More...>> 

=== mb_fb

A MicroBlaze CPU with a 24 bit high resolution graphics frame buffer held in DDR3 SDRAM, with simple demo application based on link:https://github.com/tuupola/hagl[Mike Tuupola's *hagl* graphics library]. <<./doc/mb_fb/mb_fb.adoc#,More...>>

Supports: Digilent Nexys Video

== Credits

Documentation is authored in https://asciidocfx.com/[AsciidocFX]. SVG diagrams are drawn in https://www.draw.io/[draw.io].

== License

This file is part of The Tyto Project. The Tyto Project is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

The Tyto Project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License along with The Tyto Project. If not, see https://www.gnu.org/licenses/.

